export enum AppMetaKeys {
  REQ_RES_FEATURE = 'feature',
  BODY_VALIDATOR = 'bodyValidator',
  ROUTE_URL = 'routeUrl',
  METHOD = 'method',
  ASYNC = 'async',
  STATUS_CODE = 'statusCode',
  VIEW = 'view',
  PROVIDER = 'provider',
  HANDLER_MIDDLEWARE = 'handlereMiddleware',
  ROUTER_MERGE_PARAMS = 'routerMergeParams',
  ROUTER_MERGE_PARAMS_WITH = 'routerMergeParamsWith',
  CONTROLLER_ID = 'controllerId',
  BASE_CONSTRUCTOR = 'base_constructor',
}
